
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LeoAirlines.Models
{

using System;
    using System.Collections.Generic;
    
public partial class cityinfo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public cityinfo()
    {

        this.airportinfoes = new HashSet<airportinfo>();

    }


    public string CITY { get; set; }

    public double LAT { get; set; }

    public double LONG { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<airportinfo> airportinfoes { get; set; }

}

}
